version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/mydb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
